name: Chris Ruppel
debug: false
development: false

# Environment URLs
url: https://chrisruppel.com
img-host: https://chrisruppel-assets-eu1.s3.amazonaws.com
license-url: https://github.com/rupl/chrisruppel.com/blob/master/LICENSE.md

# Jekyll config
future: true # mainly for Availability calendar
permalink: /:title/
include: [.well-known]
exclude: [README.md, LICENSE.md, package.json, gulpfile.js, Gemfile, Gemfile.lock, node_modules, .bundle, update, Procfile, vendor, index.js, bin, app.json]
keep_files: [img]
markdown: redcarpet
redcarpet:
  extensions: ["with_toc_data", "fenced_code_blocks"]

# Jekyll plugin config
tag_page_layout: tag-list
tag_page_dir: tags
tag_permalink_style: pretty

# Content types
# - Set 'output' of any collection to `true` to generate individual pages.
collections:
  clients:
    output: false
    permalink: /clients/:path/

# Set defaults for various pages
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: "posts"
      path: "travel"
    values:
      category: travel
      permalink: /travel/:title/
      layout: trip
      comments: true
      meta: true
  - scope:
      type: "pages"
      path: "travel"
    values:
      category: travel
  - scope:
      type: "posts"
      path: "blog"
    values:
      category: blog
      permalink: /blog/:title/
      layout: blog
      comments: true
      meta: true
  - scope:
      type: "pages"
      path: "blog"
    values:
      category: blog
  - scope:
      path: "about"
    values:
      layout: info
  - scope:
      path: "sandbox"
    values:
      layout: "naked"

# blank array for use within templates
array: []

# Google Analytics — the dev config unsets this value
ga: 'UA-432773-8'

# Mapbox
mapboxToken: 'pk.eyJ1IjoicnVwbCIsImEiOiI3NDc5MWQ4ZWNjMTg1ZmZlYWQ5ZjMwMWVkNjI2MTJlZCJ9.Szn0ysZDc6AjmhKnxf8PkA'

# Disqus
disqus_shortname: 'rupl'
