name: Chris Ruppel
url: https://chrisruppel.com
permalink: /:categories/:title/
debug: false
development: false

# Jekyll config
markdown: redcarpet
redcarpet:
  extensions: ["smart"]
highlighter: pygments
exclude: [README.md, LICENSE.md, package.json, gulpfile.js, Gemfile, Gemfile.lock, node_modules, .bundle, update, Procfile, vendor]

# Content types
# - Set 'output' of any collection to `true` to generate individual pages.
# collections:

# Set defaults for various pages
defaults:
  - scope:
      path: ""
    values:
      layout: default
      map: false
  - scope:
      path: "travel"
    values:
      category: travel
      layout: trip

# Google Analytics — the dev config unsets this value
ga: 'UA-432773-8'

# Mapbox
mapboxToken: 'pk.eyJ1IjoicnVwbCIsImEiOiI3NDc5MWQ4ZWNjMTg1ZmZlYWQ5ZjMwMWVkNjI2MTJlZCJ9.Szn0ysZDc6AjmhKnxf8PkA'

# Disqus
disqus_shortname: 'rupl'
