name: Chris Ruppel
url: https://chrisruppel.com
permalink: /travel/:title/
debug: false
development: false

# Jekyll config
exclude: [README.md, LICENSE.md, package.json, gulpfile.js, Gemfile, Gemfile.lock, node_modules, .bundle, update, Procfile, vendor, index.js, bin, app.json]
keep_files: [img]

# Jekyll plugin config
tag_page_layout: tags
tag_page_dir: travel/tags
tag_permalink_style: pretty

# Content types
# - Set 'output' of any collection to `true` to generate individual pages.
# collections:

# Set defaults for various pages
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: "posts"
      path: "travel"
    values:
      category: travel
      layout: trip
      comments: true
      meta: true
  - scope:
      path: "about"
    values:
      layout: info

# Google Analytics — the dev config unsets this value
ga: 'UA-432773-8'

# Mapbox
mapboxToken: 'pk.eyJ1IjoicnVwbCIsImEiOiI3NDc5MWQ4ZWNjMTg1ZmZlYWQ5ZjMwMWVkNjI2MTJlZCJ9.Szn0ysZDc6AjmhKnxf8PkA'

# Disqus
disqus_shortname: 'rupl'
