#———————————————————————————————————————————————————————————————————————————————
# Netlify-specific configuration
#———————————————————————————————————————————————————————————————————————————————

# Headers
[[headers]]
  # Global headers
  for = '/*'
  [headers.values]
    # HSTS: 190 days to bump it over 6 months.
    Strict-Transport-Security = 'max-age=16416000; includeSubDomains; preload'
    # CSP (report-only for testing)
    Content-Security-Policy-Report-Only = '''
default-src 'self';
script-src  'self' *.mapbox.com codepen.io *.codepen.io 'unsafe-inline' 'unsafe-eval';
worker-src  'self' *.mapbox.com blob:;
style-src   'self' *.mapbox.com fonts.googleapis.com 'unsafe-inline';
img-src     'self' *.mapbox.com assets.chrisruppel.com data: blob:;
connect-src 'self' *.mapbox.com assets.chrisruppel.com;
font-src    'self' fonts.gstatic.com;
frame-src   'self' codepen.io;
sandbox     allow-scripts allow-same-origin allow-popups allow-forms;
    '''
    # Allow site to iframe itself. Sometimes I use iframes for code examples.
    X-Frame-Options = 'SAMEORIGIN'
    # More secure frame assets
    X-Content-Type-Options = 'nosniff'

#———————————————————————————————————————————————————————————————————————————————
# Redirects
#———————————————————————————————————————————————————————————————————————————————

# Historical
[[redirects]]
  from = '/portfolio'
  to = '/work'
  status = 301
  force = true
[[redirects]]
  from = '/travel/list'
  to = '/travel'
  status = 301
  force = true
[[redirects]]
  from = '/blog/brave-payments/'
  to = '/blog/brave-rewards/'
  status = 301
  force = true
[[redirects]]
  from = '/blog/brave-payments-github-pages/'
  to = '/blog/brave-rewards-github-pages/'
  status = 301
  force = true
[[redirects]]
  from = '/blog/tags/*'
  to = '/tags/:splat'
  status = 301

# Web Monetization
[[redirects]]
  from = '/.well-known/pay'
  to = 'https://ilp.uphold.com/BGG9gLz6k9z9'
  status = 302
  force = true

# Fediverse discovery
[[redirects]]
  from = "/.well-known/webfinger"
  to = "https://mastodon.social/.well-known/webfinger?resource=acct:rupl@mastodon.social"
  status = 200
