#
# Netlify-specific configuration
#

#
# Headers
#
[[headers]]
  # Global headers
  for = "/*"
  [headers.values]
    # HSTS
    Strict-Transport-Security = "max-age=7776000; includeSubDomains; preload"

#
# Redirects
#
[[redirects]]
  from = "/portfolio"
  to = "/work"
  status = 301
  force = true

[[redirects]]
  from = "/blog/brave-payments/"
  to = "/blog/brave-rewards/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/brave-payments-github-pages/"
  to = "/blog/brave-rewards-github-pages/"
  status = 301
  force = true
